services:
  db:
    image: postgres:16
    container_name: chat_postgres
    restart: always
    environment:
      POSTGRES_DB: masalachatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server # See Dockerfile below
    container_name: chat_server
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: masalachatdb
      DB_USER: chatuser
      DB_PASSWORD: chatpass
    ports:
      - "5555:5555"
    volumes:
      - ./server:/app

volumes:
  db_data:
