version: "3.8"

services:
  users:
    build: ./users
    container_name: blog-users
    depends_on:
      - db
    volumes:
      - ./users/scripts:/scripts

  nginx:
    image: nginx:latest
    container_name: blog-nginx
    depends_on:
      - users
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: postgres:latest
    container_name: blog-db
    environment:
      POSTGRES_USER: hyphen
      POSTGRES_PASSWORD: hackjack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/db

volumes:
  pgdata:
