#!/bin/bash
#CREATING HOME DIRECTORIES
home_dirs=("admin" "users" "mods" "authors")
for dir in "${home_dirs[@]}"; do
    if [ -d "/home/$dir" ]; then
        :
    else
        mkdir -p "/home/$dir"
        echo "$dir directory created"
    fi
done

CONFIG_FILE="/scripts/templates/users.yaml"

#USER CREATION FUNCTION
create_user() {
    local username=$1
    local home_dir=$2
    local group_name=$3

    if id "$username" &>/dev/null; then
        echo "User $username already exists!"
    else
        useradd -m -d "$home_dir" "$username"
        usermod -a -G $group_name $username
        echo "User $username created!"
    fi
}
#USERNAME PARSING FUNCTION
get_usernames() {
    yq ".${1}[].username" "$CONFIG_FILE" | sort -u
}
#AUTHOR USERNAME PARSING FUNCTION
get_authors() {
    yq '.mods[] | select(.username == "'"$1"'") | .authors[]' "$CONFIG_FILE"
}
#ADMIN CREATION
get_usernames "admins" | while read -r username; do
    if id "$username" &>/dev/null; then
        :
    else
        home="/home/admin/$username"
        create_user "$username" "$home" "g_admin"
        chmod 700 $home
        usermod -a -G sudo $username
    fi
done

#USER CREATION
get_usernames "users" | while read -r username; do
    if id "$username" &>/dev/null; then
        :
    else
        home="/home/users/$username"
        create_user "$username" "$home" "g_user"
        mkdir -p "/home/users/$username/all_blogs"
        chmod 700 $home
    fi
done

#AUTHOR CREATION
get_usernames "authors" | while read -r username; do
    if id "$username" &>/dev/null; then
        :
    else
        home="/home/authors/$username"
        create_user "$username" "$home" "g_author"
        author_dirs=("blogs" "public")
        for dir in "${author_dirs[@]}"; do
            mkdir -p "/home/authors/$username/$dir"
        done
        cp "/scripts/templates/blogs.yaml" "/home/authors/$username/"
    fi
done

#MOD CREATION
get_usernames "mods" | while read -r username; do
    if id "$username" &>/dev/null; then
        :
    else
        home="/home/mods/$username"
        create_user "$username" "$home" "g_mod"
    fi
done

#MODERATOR PERMISSION MANAGEMENT
get_usernames "mods" | while read -r modid; do
    home="/home/mods/$modid"
    chmod 700 $home
    get_authors $modid | while read -r authorid; do
        usermod -a -G $authorid $modid
        chown $authorid:$authorid "/home/authors/$authorid"
        chmod 770 "/home/authors/$authorid"
        mkdir -p "/home/mods/$modid/AuthorDirs/$authorid"
        cp "/scripts/templates/blacklist.txt" "$home"
        ln -s "/home/authors/$authorid" "/home/mods/$modid/AuthorDirs/$authorid"
    done
done

#SYMLINK CREATION FOR USERS
authors=$(get_usernames "authors")
get_usernames "users" | while read -r user; do
    allBlogsDir="/home/users/$user/all_blogs"
    mkdir -p "$allBlogsDir"
    for author in $authors; do
        target="/home/authors/$author/public"
        linkname="$allBlogsDir/$author"
        ln -s "$target" "$linkname"
    done
    chmod 500 "$allBlogsDir"
    chmod -R 500 "$allBlogsDir"/*
    echo "All blog links created for user: $user"
done

get_usernames "mods" | while read -r mod; do
    current_groups=$(id -nG "$mod")
    new_groups=""
    for group in $current_groups; do
        if ! get_usernames "authors" | grep -qx "$group"; then
            new_groups+="$group "
        fi
    done
    usermod -G "$new_groups" "$mod"
    yq ".mods[] | select(.username == \"$mod\") | .authors[]" "$CONFIG_FILE" | while read -r authorname; do
        usermod -a -G "$authorname" "$mod"
        chown "$authorname:$authorname" "/home/authors/$authorname/public"
        chmod 770 "/home/authors/$authorname"
    done
done
